[project]
name = "winload"
version = "0.1.12"
description = "📊 Winload: A real-time terminal network traffic monitor inspired by nload. Dual implementations in 🦀Rust and 🐍Python, with cross-platform support for Windows, Linux, macOS and Android Termux. 🖥️ "
readme = "readme.md"
license = { text = "MIT" }
authors = [
    { name = "VincentZyu", email = "1830540513zyu@gmail.com" }
]
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = [
    "psutil>=7.0",
    "pyroute2>=0.9.6; sys_platform == 'linux' or sys_platform == 'android'",
    "windows-curses>=2.0; platform_system == 'Windows'",
]

[project.scripts]
winload = "winload.main:main"

[project.urls]
Homepage = "https://github.com/VincentZyuApps/winload"
Repository = "https://github.com/VincentZyuApps/winload"
Issues = "https://github.com/VincentZyuApps/winload/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/winload"]

[tool.hatch.build.targets.wheel.force-include]
"_build_info.py" = "winload/_build_info.py"

[dependency-groups]
dev = []
