#!/usr/bin/env python3
"""Generate and validate the source trees embedded in the project READMEs."""

from __future__ import annotations

import argparse
import codecs
import difflib
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import TextIO


PROJECT_ROOT = Path(__file__).resolve().parent.parent
README_FILES = (
    "readme.md",
    "readme.zh-cn.md",
    "readme.zh-tw.md",
    "readme.lzh.md",
    "readme.jp.md",
    "readme.ko.md",
)
START_MARKER = "<!-- winload-source-tree:start -->"
END_MARKER = "<!-- winload-source-tree:end -->"
GENERATED_NOTICE = (
    "<!-- Generated by scripts/update_readme_tree.py; do not edit manually. -->"
)
WARNING_LINES = 400
MAX_LINES = 500


class ValidationError(Exception):
    """Raised when source metadata or README markers are invalid."""


@dataclass(frozen=True)
class SourceFile:
    path: Path
    relative_path: Path
    role: str
    line_count: int


@dataclass
class TreeNode:
    directories: dict[str, "TreeNode"] = field(default_factory=dict)
    files: dict[str, SourceFile] = field(default_factory=dict)


@dataclass(frozen=True)
class TextDocument:
    path: Path
    text: str
    has_bom: bool
    newline: str

    def encode(self, text: str) -> bytes:
        payload = text.encode("utf-8")
        return (codecs.BOM_UTF8 + payload) if self.has_bom else payload


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Update the generated Python and Rust source trees in all READMEs."
    )
    parser.add_argument(
        "-d",
        "--dry-run",
        "--dryrun",
        dest="dry_run",
        action="store_true",
        help="show stale README sections without writing files",
    )
    return parser.parse_args(argv)


def read_document(path: Path) -> TextDocument:
    try:
        raw = path.read_bytes()
    except OSError as exc:
        raise ValidationError(f"cannot read {path}: {exc}") from exc

    has_bom = raw.startswith(codecs.BOM_UTF8)
    payload = raw[len(codecs.BOM_UTF8) :] if has_bom else raw
    try:
        text = payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValidationError(f"{path} is not valid UTF-8: {exc}") from exc

    first_lf = text.find("\n")
    newline = "\r\n" if first_lf > 0 and text[first_lf - 1] == "\r" else "\n"
    return TextDocument(path=path, text=text, has_bom=has_bom, newline=newline)


def iter_source_paths(project_root: Path) -> list[tuple[Path, str]]:
    specs = (
        (project_root / "python" / "_build_info.py", "# "),
        (project_root / "python" / "src" / "winload", "# "),
        (project_root / "rust" / "_build_info.rs", "// "),
        (project_root / "rust" / "src", "// "),
    )
    collected: list[tuple[Path, str]] = []

    for source, prefix in specs:
        if source.is_symlink():
            continue
        if source.is_file():
            collected.append((source, prefix))
            continue
        if not source.is_dir():
            raise ValidationError(f"source path does not exist: {source}")

        extension = ".py" if prefix == "# " else ".rs"
        for current, directory_names, file_names in os.walk(source, followlinks=False):
            current_path = Path(current)
            directory_names[:] = sorted(
                (
                    name
                    for name in directory_names
                    if not (current_path / name).is_symlink()
                ),
                key=lambda name: (name.casefold(), name),
            )
            for name in sorted(file_names, key=lambda name: (name.casefold(), name)):
                path = current_path / name
                if path.suffix == extension and not path.is_symlink():
                    collected.append((path, prefix))

    return sorted(
        collected,
        key=lambda item: tuple(
            (part.casefold(), part)
            for part in item[0].relative_to(project_root).parts
        ),
    )


def parse_source(path: Path, prefix: str, project_root: Path) -> SourceFile:
    document = read_document(path)
    lines = document.text.splitlines()
    relative_path = path.relative_to(project_root)
    display_path = relative_path.as_posix()
    if not lines or not lines[0].startswith(prefix):
        raise ValidationError(
            f"{display_path}: first-line role must start with {prefix!r}"
        )

    role = lines[0][len(prefix) :].strip()
    if not role or re.search(r"[A-Za-z]", role) is None:
        raise ValidationError(
            f"{display_path}: first-line role must contain a non-empty English description"
        )

    return SourceFile(
        path=path,
        relative_path=relative_path,
        role=role,
        line_count=len(lines),
    )


def collect_sources(
    project_root: Path, stderr: TextIO
) -> list[SourceFile]:
    sources = [
        parse_source(path, prefix, project_root)
        for path, prefix in iter_source_paths(project_root)
    ]
    warnings = [source for source in sources if WARNING_LINES < source.line_count <= MAX_LINES]
    violations = [source for source in sources if source.line_count > MAX_LINES]

    for source in warnings:
        print(
            f"warning: {source.relative_path.as_posix()} has {source.line_count} lines "
            f"(warning threshold: {WARNING_LINES})",
            file=stderr,
        )
    if violations:
        details = "\n".join(
            f"  - {source.relative_path.as_posix()}: {source.line_count} lines"
            for source in violations
        )
        raise ValidationError(
            f"source files exceed the {MAX_LINES}-line hard limit:\n{details}"
        )
    return sources


def add_to_tree(root: TreeNode, source: SourceFile) -> None:
    parts = source.relative_path.parts
    node = root
    for part in parts[:-1]:
        node = node.directories.setdefault(part, TreeNode())
    node.files[parts[-1]] = source


def render_children(node: TreeNode, prefix: str, output: list[str]) -> None:
    entries: list[tuple[str, bool, TreeNode | SourceFile]] = []
    entries.extend(
        (name, True, child)
        for name, child in sorted(
            node.directories.items(), key=lambda item: (item[0].casefold(), item[0])
        )
    )
    entries.extend(
        (name, False, source)
        for name, source in sorted(
            node.files.items(), key=lambda item: (item[0].casefold(), item[0])
        )
    )

    for index, (name, is_directory, value) in enumerate(entries):
        is_last = index == len(entries) - 1
        branch = "└── " if is_last else "├── "
        if is_directory:
            output.append(f"{prefix}{branch}{name}/")
            render_children(
                value,  # type: ignore[arg-type]
                prefix + ("    " if is_last else "│   "),
                output,
            )
        else:
            source = value
            assert isinstance(source, SourceFile)
            output.append(
                f"{prefix}{branch}{name} // {source.line_count} lines | {source.role}"
            )


def render_source_tree(sources: list[SourceFile]) -> str:
    tree = TreeNode()
    for source in sources:
        add_to_tree(tree, source)

    output: list[str] = []
    for root_name in ("python", "rust"):
        child = tree.directories.get(root_name)
        if child is None:
            raise ValidationError(f"source tree has no {root_name}/ entries")
        if output:
            output.append("")
        output.append(f"{root_name}/")
        render_children(child, "", output)
    return "\n".join(output)


def generated_block(tree: str, newline: str) -> str:
    lines = (
        START_MARKER,
        GENERATED_NOTICE,
        "```text",
        *tree.splitlines(),
        "```",
        END_MARKER,
    )
    return newline.join(lines)


def replace_generated_block(document: TextDocument, tree: str) -> str:
    text = document.text
    relative_path = document.path.name
    if text.count(START_MARKER) != 1 or text.count(END_MARKER) != 1:
        raise ValidationError(
            f"{relative_path}: expected exactly one start marker and one end marker"
        )
    start_matches = list(
        re.finditer(rf"(?m)^{re.escape(START_MARKER)}(?=\r?$)", text)
    )
    end_matches = list(
        re.finditer(rf"(?m)^{re.escape(END_MARKER)}(?=\r?$)", text)
    )
    if len(start_matches) != 1 or len(end_matches) != 1:
        raise ValidationError(
            f"{relative_path}: expected exactly one start marker and one end marker"
        )

    start = start_matches[0]
    end = end_matches[0]
    if start.start() >= end.start():
        raise ValidationError(f"{relative_path}: source-tree markers are out of order")
    suffix = text[end.end() :]
    if suffix.strip():
        raise ValidationError(
            f"{relative_path}: source-tree section must be the final README section"
        )
    return text[: start.start()] + generated_block(tree, document.newline) + suffix


def unified_diff(path: Path, old: str, new: str) -> str:
    return "\n".join(
        difflib.unified_diff(
            old.splitlines(),
            new.splitlines(),
            fromfile=str(path),
            tofile=str(path),
            lineterm="",
        )
    )


def run(
    project_root: Path,
    dry_run: bool,
    stdout: TextIO = sys.stdout,
    stderr: TextIO = sys.stderr,
) -> int:
    try:
        sources = collect_sources(project_root, stderr)
        tree = render_source_tree(sources)
        documents = [read_document(project_root / name) for name in README_FILES]
        replacements = [
            (document, replace_generated_block(document, tree))
            for document in documents
        ]
    except ValidationError as exc:
        print(f"error: {exc}", file=stderr)
        return 2

    stale = [(document, new) for document, new in replacements if new != document.text]
    if dry_run:
        for document, new in stale:
            print(unified_diff(document.path, document.text, new), file=stdout)
        return 1 if stale else 0

    for document, new in stale:
        try:
            document.path.write_bytes(document.encode(new))
        except OSError as exc:
            print(f"error: cannot write {document.path}: {exc}", file=stderr)
            return 2
        print(f"updated {document.path.relative_to(project_root).as_posix()}", file=stdout)
    return 0


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    return run(PROJECT_ROOT, args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
